on: pull_request
name: Slack PR Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'A new PR was created!'
          SLACK_COLOR: '#3278BD'
          SLACK_MESSAGE: '${{ github.actor }} created new PR on ${{ github.repository}}'
